# Generated by Django 6.0.2 on 2026-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMenuElem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, verbose_name='Команда')),
                ('is_visable', models.BooleanField(default=True, verbose_name='Видим?')),
                ('callbacks_db', models.CharField(blank=True, max_length=255, null=True, verbose_name='Callback data')),
                ('message', models.TextField(verbose_name='Сообщение от бота')),
                ('buttons_db', models.JSONField(blank=True, default=dict, verbose_name='Кнопки (JSON)')),
            ],
            options={
                'verbose_name': 'Элемент меню бота',
                'verbose_name_plural': 'Элементы меню бота',
            },
        ),
    ]
