# Generated by Django 5.2.4 on 2026-01-03 10:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', verbose_name='URL'),
        ),
    ]
