# Generated by Django 5.2.4 on 2026-01-03 11:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
