# Generated by Django 5.2.4 on 2026-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
